# Generated by Django 4.2 on 2023-04-29 18:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Requetes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20)),
                ('matricule', models.CharField(max_length=20)),
                ('lieu_de_naissance', models.CharField(max_length=20)),
                ('numero_CNI', models.CharField(max_length=20)),
                ('aptitude', models.CharField(choices=[('APTE', 'APTE'), ('INAPTE', 'INAPTE')], max_length=20)),
                ('role', models.CharField(choices=[('DIRECTEUR', 'DIRECTEUR'), ('CHEF DE DEPARTEMENT', 'CHEF DE DEPARTEMENT'), ('RESPONSABLE DE SERVICE', 'RESPONSABLE DE SERVICE'), ('ENSEIGNANT', 'ENSEIGNANT'), ('ETUDIANT', 'ETUDIANT')], max_length=40)),
                ('pays', django_countries.fields.CountryField(max_length=2)),
                ('sexe', models.CharField(choices=[('HOMME', 'HOMME'), ('FEMME', 'FEMME')], max_length=20)),
                ('date_naissance', models.DateField(default=datetime.date(1990, 1, 1))),
                ('image', models.ImageField(default='avatar.jpg', upload_to='Profile_Images')),
                ('departements', models.ManyToManyField(blank=True, to='Requetes.departement')),
                ('services', models.ManyToManyField(blank=True, to='Requetes.service')),
                ('utilisateur', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
    ]
