# Generated by Django 4.2 on 2023-04-29 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Requetes', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEMANDE DE DIPLOME', 'DEMANDE DE DIPLOME'), ('DEMANDE DE CORRECTION DE NOTE', 'DEMANDE DE CORRECTION DE NOTE'), ('DEMANDE DE TRANSFERT DE FILIERE', 'DEMANDE DE TRANSFERT DE FILIERE'), ('DEMANDE DE REEXAMEN', 'DEMANDE DE REEXAMEN'), ("DEMANDE D'ORIENTATION ACADEMIQUE", "DEMANDE D'ORIENTATION ACADEMIQUE"), ('DEMANDE DE SOUTIENT PEDAGOGIQUE', 'DEMANDE DE SOUTIEN PEDAGOGIQUE'), ("DEMANDE D'UNE AUTORISATION D'ABSENCE", "DEMANDE D'UNE AUTORISATION D'ABSENCE"), ("JUSTIFICATION D'ABSENCES", "JUSTIFICATION D'ABSENCES"), ('AUTRES', 'AUTRES')], max_length=40)),
                ('objet', models.CharField(max_length=200)),
                ('contenu', models.TextField(max_length=2000)),
                ('remarque', models.TextField(blank=True, max_length=300)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('statut', models.CharField(choices=[('EN ATTENTE DE TRAITEMENT', 'EN ATTENTE DE TRAITEMENT'), ('EN COURS DE TRAITEMENT', 'EN COURS DE TRAITEMENT'), ("EN ATTENTE DE COMPLEMENT D'INFORMATION", "EN ATTENTE DE COMPLEMENT D'INFORMATION"), ('EN ATTENTE DE TRAITEMENT', 'EN ATTENTE DE TRAITEMENT'), ('ACCEPTE', 'ACCEPTE'), ('EN APPEL', 'EN APPEL'), ('REFUSE', 'REFUSE'), ('CLOTURE', 'CLOTURE')], max_length=40)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Requetes.departement')),
                ('destinataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinataire_requetes', to='Requetes.profile')),
                ('expediteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expediteur_requetes', to='Requetes.profile')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Requetes.service')),
            ],
            options={
                'db_table': 'Requete',
            },
        ),
    ]
