# Generated by Django 4.2 on 2023-04-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requetes', '0003_requete'),
    ]

    operations = [
        migrations.AddField(
            model_name='requete',
            name='lu',
            field=models.BooleanField(default=False),
        ),
    ]
